# Generated by Django 2.1.7 on 2019-04-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190412_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='to_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='cv',
            field=models.URLField(max_length=320),
        ),
    ]
