# Generated by Django 2.1.7 on 2019-04-13 02:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190412_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-to_date', '-from_date'], 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-from_date', '-to_date'], 'verbose_name_plural': 'Experience'},
        ),
        migrations.AlterField(
            model_name='about',
            name='cv',
            field=models.FileField(max_length=320, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Image'),
        ),
    ]
